using Newtonsoft.Json;
using NUnit.Framework;
using SFB.Web.ApplicationCore.Entities;
using Assert = NUnit.Framework.Legacy.ClassicAssert;

namespace SFB.Artifacts.UnitTests.Serialization;

public class SchoolTrustFinancialDataObjectDeserializationTests
{
    [Test]
    // 20200706000000-Maintained-2018-2019
    public void DeserializeSchoolTrustFinancialDataObject_IntsAsInts_ParsesSuccessfully()
    {
        // arrange
        const string document = @"{
    ""School Name"": ""Roughlee Church Of England Primary School"",
    ""Gender"": ""Mixed"",
    ""Overall Phase"": ""Primary"",
    ""Phase"": ""Infant and junior"",
    ""Type"": ""Voluntary controlled school"",
    ""Region"": ""North West"",
    ""Has a 6th form"": false,
    ""Average Key Stage 2 Point score"": null,
    ""Average GCSE and equivalent point score (not capped)"": null,
    ""Funding for minority ethnic pupils"": 0,
    ""Receipts from other insurance claims"": 0,
    ""Income from contributions to visits etc"": 0,
    ""Pupil focussed extended school funding and/or grants"": 0,
    ""Community focussed school funding and/or grants"": 0,
    ""Community focused school facilities income"": 0,
    ""Additional grant for schools"": 25021,
    ""Rates"": 295,
    ""Community focused school staff"": 0,
    ""Community focused school costs"": 0,
    ""UrbanRuralDetail"": ""Rural village"",
    ""UrbanRuralInner"": ""Rural and village"",
    ""UrbanRuralOuter"": ""Rural"",
    ""Estab"": 3094,
    ""LA"": 888,
    ""PercentageOfAllTeachingStaffWhoWorkPartTime"": 0,
    ""PupilTeacherRatio"": 14,
    ""TeachersWithQualifiedTeacherStatus"": 66.7,
    ""LAEstab"": 8883094,
    ""URN"": 119383,
    ""Period covered by return"": 12,
    ""% of pupils with SEN Statement"": 0,
    ""% of pupils with EAL"": 11.9,
    ""% of pupils who are Boarders"": 0,
    ""No of pupils in 6th form"": 0,
    ""Lowest age of pupils"": 4,
    ""Highest age of pupils"": 11,
    ""% achieving Level 4 including English and Maths at KS2"": null,
    ""% with 5 A*-C grade GCSEs (or equiv) inc English and Maths"": null,
    ""Post-16 Funding"": 0,
    ""Other DfE/EFA Revenue Grants"": 0,
    ""Receipts from supply teacher insurance claims"": 0,
    ""Supply teaching staff"": 0,
    ""Premises staff"": 6958,
    ""Supply teacher insurance"": 2308,
    ""Water and sewerage"": 1608,
    ""Energy"": 3864,
    ""Special facilities"": 0,
    ""Examination fees"": 0,
    ""Interest charges for Loan and Bank"": 0,
    ""Community Grants"": 25021,
    ""Community Exp"": 0,
    ""Primary_need_mld"": 7,
    ""Primary_need_semh"": 1,
    ""Primary_need_oth"": 0,
    ""Primary_need_mld_percent"": 16.67,
    ""Primary_need_semh_percent"": 2.38,
    ""Primary_need_oth_percent"": 0,
    ""TotalNumberOfClassroomTeachersHeadcount"": 2,
    ""TotalNumberOfClassroomTeachersFullTimeEquivalent"": 2,
    ""RatioOfTeachingAssistantsToAllTeachers"": 0.5,
    ""AllTeachingAssistantsThatAreHLTAs"": 0,
    ""Admissions policy"": ""N/A"",
    ""PTRWM_EXP"": 86,
    ""WRITPROG"": 4.4,
    ""READPROG"": -0.1,
    ""MATPROG"": null,
    ""KS2 Progress"": 1.3,
    ""Primary_need_spld"": 0,
    ""Primary_need_sld"": 0,
    ""Primary_need_pmld"": 0,
    ""Primary_need_slcn"": 1,
    ""Primary_need_hi"": 0,
    ""Primary_need_vi"": 0,
    ""Primary_need_msi"": 0,
    ""Primary_need_pd"": 0,
    ""Primary_need_asd"": 0,
    ""Primary_need_asd_percent"": 0,
    ""Primary_need_hi_percent"": 0,
    ""Primary_need_msi_percent"": 0,
    ""Primary_need_pd_percent"": 0,
    ""Primary_need_pmld_percent"": 0,
    ""Primary_need_slcn_percent"": 2.38,
    ""Primary_need_sld_percent"": 0,
    ""Primary_need_spld_percent"": 0,
    ""Primary_need_vi_percent"": 0,
    ""OfstedRating"": ""2"",
    ""OfstedRatingName"": ""Good"",
    ""OfstedLastInsp"": ""28-06-2017"",
    ""Federation Y/N"": ""N"",
    ""No Pupils"": 42,
    ""No Teachers"": 3,
    ""London Borough"": ""Neither"",
    ""London Weighting"": ""Neither"",
    ""% of pupils eligible for FSM"": 23.8,
    ""% of SEN pupils without Statement"": 21.4,
    ""PFI"": ""Not Part Of PFI"",
    ""% of teachers with QTS"": 66.7,
    ""FTE of Teaching Assistants"": 1.5,
    ""FTE of Support Staff"": 0.8,
    ""FTE of Admin Staff"": 0.4,
    ""Pre-16 Funding"": 306553,
    ""SEN"": 0,
    ""Pupil Premium"": 17880,
    ""Other income (LA & other Government grants)"": null,
    ""Income from facilities and services"": 464,
    ""Income from catering"": 2452,
    ""Donations and/or voluntary funds"": 0,
    ""Teaching staff"": 154022,
    ""Education support staff"": 34683,
    ""Administrative and clerical staff"": 9979,
    ""Catering staff"": 0,
    ""Other staff"": 5379,
    ""Indirect employee expenses"": 971,
    ""Staff development and training"": 2559,
    ""Staff-related insurance"": 0,
    ""Building maintenance and improvement"": 53076,
    ""Grounds maintenance and improvement"": 146,
    ""Cleaning and caretaking"": 480,
    ""Other occupation costs"": 325,
    ""Learning resources (not ICT equipment)"": 14541,
    ""ICT learning resources"": 2353,
    ""Educational Consultancy"": 11264,
    ""Administrative supplies - non educational"": 4667,
    ""Agency supply teaching staff"": 0,
    ""Catering supplies"": 18453,
    ""Other insurance premiums"": 4043,
    ""Bought in professional services / other"": 19078,
    ""Direct revenue financing (Revenue contributions to capital)"": 0,
    ""Revenue Reserve"": 53790,
    ""In Year Balance"": 1318,
    ""Grant Funding"": 349454,
    ""Direct Grant"": 306553,
    ""Targeted Grants"": 17880,
    ""Self Generated Funding"": 2916,
    ""Total Income"": 352370,
    ""Supply Staff"": 2308,
    ""Other Staff Costs"": 8909,
    ""Staff Total"": 209901,
    ""Maintenance & Improvement"": 53222,
    ""Premises"": 60660,
    ""Catering Exp"": 18453,
    ""Occupation"": 28588,
    ""Supplies and Services"": 51903,
    ""Educational Supplies"": 16894,
    ""Brought in Professional Sevices"": 30342,
    ""Cost of Finance"": 0,
    ""Total Expenditure"": 351052,
    ""RevenueReserveAsSubmitted"": 53790,
    ""DNS"": false,
    ""WorkforcePresent"": true,
    ""SpecialNeedsPresent"": true,
    ""KS2Present"": true,
    ""KS4Present"": false,
    ""OfstedPresent"": true,
    ""TotalSchoolWorkforceHeadcount"": 10,
    ""TotalSchoolWorkforceFullTimeEquivalent"": 5.7,
    ""TotalNumberOfTeachersHeadcount"": 3,
    ""TotalNumberOfTeachersFullTimeEquivalent"": 3,
    ""TotalNumberOfTeachersInTheLeadershipGroupHeadcount"": 1,
    ""TotalNumberOfTeachersInTheLeadershipGroupFullTimeEquivalent"": 1,
    ""TotalNumberOfTeachingAssistantsHeadcount"": 3,
    ""TotalNumberOfTeachingAssistantsFullTimeEquivalent"": 1.5,
    ""TotalNumberOfNonClassroomBasedSchoolSupportStaffExcludingAuxiliaryStaffHeadcount"": 0.8,
    ""TotalNumberOfNonClassroomBasedSchoolSupportStaffExcludingAuxiliaryStaffFullTimeEquivalent"": 0.8,
    ""TotalNumberOfAuxiliaryStaffHeadcount"": 1,
    ""TotalNumberOfAuxiliaryStaffFullTimeEquivalent"": 0.4,
    ""last-modified-date-time"": ""2020-07-06T16:41:00.737"",
    ""PerPupilGrantFunding"": 8320.33,
    ""PercentRevenueReserveOfTotalIncome"": 15.27,
    ""PerPupilTotalExpenditure"": 8358.38,
    ""PerPupilTotalSchoolWorkforceHeadcount"": 4.2,
    ""PerPupilTotalSchoolWorkforceFullTimeEquivalent"": 7.37,
    ""PerPupilTotalNumberOfTeachersHeadcount"": 14,
    ""PerPupilTotalNumberOfTeachersFullTimeEquivalent"": 14,
    ""PerPupilTotalNumberOfTeachersInTheLeadershipGroupHeadcount"": 42,
    ""PerPupilTotalNumberOfTeachersInTheLeadershipGroupFullTimeEquivalent"": 42,
    ""PerPupilTotalNumberOfTeachingAssistantsHeadcount"": 14,
    ""PerPupilTotalNumberOfTeachingAssistantsFullTimeEquivalent"": 28,
    ""PerPupilTotalNumberOfAuxiliaryStaffHeadcount"": 28,
    ""PerPupilTotalNumberOfAuxiliaryStaffFullTimeEquivalent"": 105,
    ""PerPupilTotalNumberOfNonClassroomBasedSchoolSupportStaffExcludingAuxiliaryStaffHeadcount"": 52.5,
    ""PerPupilTotalNumberOfNonClassroomBasedSchoolSupportStaffExcludingAuxiliaryStaffFullTimeEquivalent"": 52.5,
    ""RatioTotalNumberOfTeachersFullTimeEquivalent"": 1.75,
    ""RatioTotalNumberOfTeachingAssistantsFullTimeEquivalent"": 2,
    ""RatioTotalNumberOfNonClassroomBasedSchoolSupportStaffExcludingAuxiliaryStaffFullTimeEquivalent"": 1,
    ""RatioTotalNumberOfAuxiliaryStaffFullTimeEquivalent"": 2.5,
    ""PercentTotalNumberOfTeachersInTheLeadershipGroupFullTimeEquivalent"": 10,
    ""PercentTotalNumberOfTeachingAssistantsHeadcount"": 30,
    ""PercentTotalNumberOfTeachingAssistantsFullTimeEquivalent"": 15,
    ""RegionalPaySpine"": ""EW"",
    ""MeanGrossSalaryOfAllTeachers"": 40021,
    ""AllClassroomTeachersOnMainPayRangePercent"": null,
    ""AllClassroomTeachersOnUpperPayRangeAndOrLeadingPractionersPayRangePercent"": null,
    ""AllQualifiedClassroomTeachersReceivingAnyAllowancePercent"": null,
    ""AllTeachersOnTheLeadershipPayRangePercent"": null,
    ""id"": ""d7638cdb-35c7-4813-909c-2f6a09de72b9"",
    ""_rid"": ""qgt3AK4s2b0BAAAAAAAAAA=="",
    ""_self"": ""dbs/qgt3AA==/colls/qgt3AK4s2b0=/docs/qgt3AK4s2b0BAAAAAAAAAA==/"",
    ""_etag"": ""\""210043da-0000-0d00-0000-61388c6f0000\"""",
    ""_attachments"": ""attachments/"",
    ""Pre-16 and 6th form funding"": 306553,
    ""_ts"": 1631095919
}";

        // act
        var parsed = JsonConvert.DeserializeObject<SchoolTrustFinancialDataObject>(document);

        // assert
        Assert.AreEqual(119383, parsed.URN);
        Assert.AreEqual(12, parsed.PeriodCoveredByReturn);
        Assert.AreEqual(4, parsed.LowestAgePupils);
        Assert.AreEqual(11, parsed.HighestAgePupils);
    }

    [Test]
    // 20221012000000-Maintained-2021-2022
    public void DeserializeSchoolTrustFinancialDataObject_IntAsDecimals_ParsesSuccessfully()
    {
        // arrange
        const string document = @"{
  ""School Name"": ""Ireland Wood Primary School"",
  ""Gender"": ""Mixed"",
  ""Overall Phase"": ""Primary"",
  ""Phase"": ""Infant and junior"",
  ""Type"": ""Foundation school"",
  ""Region"": ""Yorkshire and the Humber"",
  ""Has a 6th form"": false,
  ""Average Key Stage 2 Point score"": null,
  ""Average GCSE and equivalent point score (not capped)"": null,
  ""Funding for minority ethnic pupils"": 0.0,
  ""Receipts from other insurance claims"": 0.0,
  ""Income from contributions to visits etc"": 0.0,
  ""Pupil focussed extended school funding and/or grants"": 93452.0,
  ""Community focussed school funding and/or grants"": 0.0,
  ""Community focused school facilities income"": 0.0,
  ""Additional grant for schools"": 78552.0,
  ""Rates"": 5888.0,
  ""Community focused school staff"": 0.0,
  ""Community focused school costs"": 0.0,
  ""UrbanRuralDetail"": ""Urban major conurbation"",
  ""UrbanRuralInner"": ""Conurbation"",
  ""UrbanRuralOuter"": ""Urban"",
  ""Estab"": 2420,
  ""LA"": 383,
  ""PercentageOfAllTeachingStaffWhoWorkPartTime"": 20.0,
  ""PupilTeacherRatio"": 18.3,
  ""TeachersWithQualifiedTeacherStatus"": 100.0,
  ""LAEstab"": 3832420,
  ""URN"": 107896,
  ""Period covered by return"": 12.0,
  ""% of pupils with SEN Statement"": 5.0,
  ""% of pupils with EAL"": 16.9,
  ""% of pupils who are Boarders"": 0.0,
  ""No of pupils in 6th form"": 0.0,
  ""Lowest age of pupils"": 5.0,
  ""Highest age of pupils"": 11.0,
  ""% achieving Level 4 including English and Maths at KS2"": null,
  ""% with 5 A*-C grade GCSEs (or equiv) inc English and Maths"": null,
  ""Post-16 Funding"": 2001706.0,
  ""Other DfE/EFA Revenue Grants"": 0.0,
  ""Receipts from supply teacher insurance claims"": 0.0,
  ""Supply teaching staff"": 0.0,
  ""Premises staff"": 84535.0,
  ""Supply teacher insurance"": 16975.0,
  ""Water and sewerage"": 7966.0,
  ""Energy"": 39794.0,
  ""Special facilities"": 38580.0,
  ""Examination fees"": 0.0,
  ""Interest charges for Loan and Bank"": null,
  ""Community Grants"": 78552.0,
  ""Community Exp"": 0.0,
  ""Primary_need_mld"": 8.0,
  ""Primary_need_semh"": 12.0,
  ""Primary_need_oth"": 7.0,
  ""Primary_need_mld_percent"": 1.91,
  ""Primary_need_semh_percent"": 2.86,
  ""Primary_need_oth_percent"": 1.67,
  ""TotalNumberOfClassroomTeachersHeadcount"": 20.0,
  ""TotalNumberOfClassroomTeachersFullTimeEquivalent"": 18.09,
  ""RatioOfTeachingAssistantsToAllTeachers"": 1.68,
  ""AllTeachingAssistantsThatAreHLTAs"": null,
  ""Admissions policy"": ""N/A"",
  ""PTRWM_EXP"": 62.0,
  ""WRITPROG"": 2.6,
  ""READPROG"": 2.2,
  ""MATPROG"": null,
  ""KS2 Progress"": 2.53,
  ""P8MEA"": null,
  ""ATT8SCR"": null,
  ""Primary_need_spld"": 3.0,
  ""Primary_need_sld"": 2.0,
  ""Primary_need_pmld"": 0.0,
  ""Primary_need_slcn"": 25.0,
  ""Primary_need_hi"": 0.0,
  ""Primary_need_vi"": 1.0,
  ""Primary_need_msi"": 0.0,
  ""Primary_need_pd"": 10.0,
  ""Primary_need_asd"": 12.0,
  ""Primary_need_asd_percent"": 2.86,
  ""Primary_need_hi_percent"": 0.0,
  ""Primary_need_msi_percent"": 0.0,
  ""Primary_need_pd_percent"": 2.39,
  ""Primary_need_pmld_percent"": 0.0,
  ""Primary_need_slcn_percent"": 5.97,
  ""Primary_need_sld_percent"": 0.48,
  ""Primary_need_spld_percent"": 0.72,
  ""Primary_need_vi_percent"": 0.24,
  ""OfstedRating"": ""2"",
  ""OfstedRatingName"": ""Good"",
  ""OfstedLastInsp"": ""31-01-2017"",
  ""Federation Y/N"": ""No"",
  ""No Pupils"": 419.0,
  ""No Teachers"": 22.9,
  ""London Borough"": ""Neither"",
  ""London Weighting"": ""Neither"",
  ""% of pupils eligible for FSM"": 31.5,
  ""% of SEN pupils without Statement"": 14.1,
  ""PFI"": ""Not Part Of PFI"",
  ""% of teachers with QTS"": null,
  ""FTE of Teaching Assistants"": null,
  ""FTE of Support Staff"": null,
  ""FTE of Admin Staff"": null,
  ""Pre-16 Funding"": 2001706.0,
  ""SEN"": 296764.0,
  ""Pupil Premium"": 174855.0,
  ""Other income (LA \u0026 other Government grants)"": 14635.0,
  ""Income from facilities and services"": 36702.0,
  ""Income from catering"": 20781.0,
  ""Donations and/or voluntary funds"": 0.0,
  ""Teaching staff"": 936297.0,
  ""Education support staff"": 1024142.0,
  ""Administrative and clerical staff"": 111329.0,
  ""Catering staff"": 0.0,
  ""Other staff"": 55043.0,
  ""Indirect employee expenses"": 5722.0,
  ""Staff development and training"": 4357.0,
  ""Staff-related insurance"": 3242.0,
  ""Building maintenance and improvement"": 29048.0,
  ""Grounds maintenance and improvement"": 4584.0,
  ""Cleaning and caretaking"": 0.0,
  ""Other occupation costs"": 26296.0,
  ""Learning resources (not ICT equipment)"": 74330.0,
  ""ICT learning resources"": 11284.0,
  ""Educational Consultancy"": 73197.0,
  ""Administrative supplies - non educational"": 6341.0,
  ""Agency supply teaching staff"": 0.0,
  ""Catering supplies"": 119707.0,
  ""Other insurance premiums"": 20031.0,
  ""Direct revenue financing (Revenue contributions to capital)"": null,
  ""Revenue Reserve"": 8515.0,
  ""In Year Balance"": 3102.0,
  ""Grant Funding"": 2659964.0,
  ""Direct Grant"": 2016341.0,
  ""Targeted Grants"": 565071.0,
  ""Self Generated Funding"": 58323.0,
  ""Total Income"": 2718287.0,
  ""Supply Staff"": 16975.0,
  ""Other Staff Costs"": 68364.0,
  ""Staff Total"": 2157107.0,
  ""Maintenance \u0026 Improvement"": 33632.0,
  ""Premises"": 118167.0,
  ""Catering Exp"": 119707.0,
  ""Occupation"": 219682.0,
  ""Supplies and Services"": 181649.0,
  ""Educational Supplies"": 85614.0,
  ""Brought in Professional Sevices"": 89694.0,
  ""Cost of Finance"": null,
  ""Total Expenditure"": 2715185.0,
  ""RevenueReserveAsSubmitted"": 8515.0,
  ""DNS"": false,
  ""WorkforcePresent"": true,
  ""SpecialNeedsPresent"": true,
  ""KS2Present"": true,
  ""KS4Present"": false,
  ""OfstedPresent"": true,
  ""TotalSchoolWorkforceHeadcount"": 107.0,
  ""TotalSchoolWorkforceFullTimeEquivalent"": 72.56,
  ""TotalNumberOfTeachersHeadcount"": 25.0,
  ""TotalNumberOfTeachersFullTimeEquivalent"": 22.89,
  ""TotalNumberOfTeachersInTheLeadershipGroupHeadcount"": 5.0,
  ""TotalNumberOfTeachersInTheLeadershipGroupFullTimeEquivalent"": 4.8,
  ""TotalNumberOfTeachingAssistantsHeadcount"": 54.0,
  ""TotalNumberOfTeachingAssistantsFullTimeEquivalent"": 38.36,
  ""TotalNumberOfNonClassroomBasedSchoolSupportStaffExcludingAuxiliaryStaffHeadcount"": 11.0,
  ""TotalNumberOfNonClassroomBasedSchoolSupportStaffExcludingAuxiliaryStaffFullTimeEquivalent"": 5.79,
  ""TotalNumberOfAuxiliaryStaffHeadcount"": 17.0,
  ""TotalNumberOfAuxiliaryStaffFullTimeEquivalent"": 5.52,
  ""last-modified-date-time"": null,
  ""PerPupilGrantFunding"": 6348.36,
  ""PercentRevenueReserveOfTotalIncome"": 0.31,
  ""PerPupilTotalExpenditure"": 6480.16,
  ""PerPupilTotalSchoolWorkforceHeadcount"": null,
  ""PerPupilTotalSchoolWorkforceFullTimeEquivalent"": null,
  ""PerPupilTotalNumberOfTeachersHeadcount"": null,
  ""PerPupilTotalNumberOfTeachersFullTimeEquivalent"": null,
  ""PerPupilTotalNumberOfTeachersInTheLeadershipGroupHeadcount"": null,
  ""PerPupilTotalNumberOfTeachersInTheLeadershipGroupFullTimeEquivalent"": null,
  ""PerPupilTotalNumberOfTeachingAssistantsHeadcount"": null,
  ""PerPupilTotalNumberOfTeachingAssistantsFullTimeEquivalent"": null,
  ""PerPupilTotalNumberOfAuxiliaryStaffHeadcount"": null,
  ""PerPupilTotalNumberOfAuxiliaryStaffFullTimeEquivalent"": null,
  ""PerPupilTotalNumberOfNonClassroomBasedSchoolSupportStaffExcludingAuxiliaryStaffHeadcount"": null,
  ""PerPupilTotalNumberOfNonClassroomBasedSchoolSupportStaffExcludingAuxiliaryStaffFullTimeEquivalent"": null,
  ""RatioTotalNumberOfTeachersFullTimeEquivalent"": null,
  ""RatioTotalNumberOfTeachingAssistantsFullTimeEquivalent"": null,
  ""RatioTotalNumberOfNonClassroomBasedSchoolSupportStaffExcludingAuxiliaryStaffFullTimeEquivalent"": null,
  ""RatioTotalNumberOfAuxiliaryStaffFullTimeEquivalent"": null,
  ""PercentTotalNumberOfTeachersInTheLeadershipGroupFullTimeEquivalent"": null,
  ""PercentTotalNumberOfTeachingAssistantsHeadcount"": null,
  ""PercentTotalNumberOfTeachingAssistantsFullTimeEquivalent"": null,
  ""RegionalPaySpine"": ""EW"",
  ""MeanGrossSalaryOfAllTeachers"": 38052.0,
  ""AllClassroomTeachersOnMainPayRangePercent"": null,
  ""AllClassroomTeachersOnUpperPayRangeAndOrLeadingPractionersPayRangePercent"": null,
  ""AllQualifiedClassroomTeachersReceivingAnyAllowancePercent"": null,
  ""AllTeachersOnTheLeadershipPayRangePercent"": 20.0,
  ""P8_BANDING"": null,
  ""IsFederation"": false,
  ""FederationMembers"": null,
  ""IsLeadSchool"": false,
  ""IsPartOfFederation"": false,
  ""FederationUID"": null,
  ""FederationName"": null,
  ""NurseryProvisionName"": null,
  ""Pre-16 and 6th form funding"": 2001706.0,
  ""BoughtInProfessionalServicesOtherNotPFI"": 16497.0,
  ""InterestChargesForLoansAndBank"": 0.0,
  ""DirectRevenueFinancingCapitalReserveTransfers"": 0.0,
  ""PFI Charges"": 0.0,
  ""id"": ""430d48ef-28aa-4857-9081-cd76d8e935b9"",
  ""_rid"": ""qgt3AKBLXZYiMAAAAAAAAA\u003d\u003d"",
  ""_self"": ""dbs/qgt3AA\u003d\u003d/colls/qgt3AKBLXZY\u003d/docs/qgt3AKBLXZYiMAAAAAAAAA\u003d\u003d/"",
  ""_etag"": ""\""1100585f-0000-0d00-0000-64476fa60000\"""",
  ""_attachments"": ""attachments/"",
  ""% of pupils without SEN Statement"": 14.1,
  ""_ts"": 1682403238
}";

        // act
        var parsed = JsonConvert.DeserializeObject<SchoolTrustFinancialDataObject>(document);

        // assert
        Assert.AreEqual(107896, parsed.URN);
        Assert.AreEqual(12, parsed.PeriodCoveredByReturn);
        Assert.AreEqual(5, parsed.LowestAgePupils);
        Assert.AreEqual(11, parsed.HighestAgePupils);
    }

    [Test]
    // 20200421000000-MAT-Overview-2018-2019
    public void DeserializeSchoolTrustFinancialDataObject_Trust_ParsesSuccessfully()
    {
        // arrange
        const string document = @"{
  ""LA"": null,
  ""Estab"": null,
  ""URN"": null,
  ""UID"": 4850,
  ""School Name"": null,
  ""Period covered by return"": 12,
  ""MAT SAT or Central Services"": ""Central services"",
  ""Lead UPIN"": 137255,
  ""Date closed if in period"": null,
  ""Date opened if in period"": null,
  ""Gender"": null,
  ""Phase"": null,
  ""Overall PhaseBreakdown"": {
    ""Primary"": 8,
    ""Secondary"": 0,
    ""Special"": 0,
    ""Pupil referral unit"": 0,
    ""All-through"": 0,
    ""16 plus"": 0
  },
  ""Type"": null,
  ""Urban /Rural"": null,
  ""Region"": null,
  ""London Borough"": null,
  ""London Weighting"": null,
  ""% of pupils eligible for FSM"": null,
  ""% of pupils with SEN Statement"": 11.675,
  ""DirectRevenueFinancingCapitalReserveTransfers"": -164000.0,
  ""InterestChargesForLoansAndBank"": 0.0,
  ""% of pupils without SEN Statement"": 2.5375,
  ""% of pupils with EAL"": null,
  ""% of pupils who are Boarders"": null,
  ""Admissions policy"": null,
  ""PFI"": null,
  ""Has a 6th form"": false,
  ""No of pupils in 6th form"": 0.0,
  ""Lowest age of pupils"": null,
  ""Highest age of pupils"": null,
  ""SEN"": 614000.0,
  ""Other DfE/EFA Revenue Grants"": 667000.0,
  ""Other income (LA & other Government grants)"": 0.0,
  ""Government source (non-grant)"": 0.0,
  ""Academies"": 0.0,
  ""Non- Government"": 30000.0,
  ""Income from facilities and services"": 117000.0,
  ""Income from catering"": 0.0,
  ""Receipts from supply teacher insurance claims"": 32000.0,
  ""Donations and/or voluntary funds"": 26000.0,
  ""Other self-generated income"": 23000.0,
  ""Investment income"": 0.0,
  ""Teaching staff"": 5553000.0,
  ""Supply teaching staff"": 0.0,
  ""Education support staff"": 2067000.0,
  ""Administrative and clerical staff"": 1307000.0,
  ""Premises staff"": 148000.0,
  ""Catering staff"": 0.0,
  ""Other staff"": 440000.0,
  ""Indirect employee expenses"": 5000.0,
  ""Staff development and training"": 66000.0,
  ""Staff-related insurance"": 45000.0,
  ""Supply teacher insurance"": 0.0,
  ""Building and Grounds maintenance and improvement"": 253000.0,
  ""Cleaning and caretaking"": 206000.0,
  ""Water and sewerage"": 26000.0,
  ""Energy"": 92000.0,
  ""Rent and Rates"": 56000.0,
  ""Other occupation costs"": 95000.0,
  ""Special facilities"": 26000.0,
  ""Learning resources (not ICT equipment)"": 465000.0,
  ""ICT learning resources"": 36000.0,
  ""Examination fees"": 0.0,
  ""Educational Consultancy"": 9000.0,
  ""Administrative supplies - non educational"": 559000.0,
  ""Agency supply teaching staff"": 170000.0,
  ""Catering supplies"": 321000.0,
  ""Other insurance premiums"": 37000.0,
  ""Legal & Professional"": 56000.0,
  ""Auditor costs"": 31000.0,
  ""Interest charges for Loan and Bank"": null,
  ""Direct revenue financing (Revenue contributions to capital)"": null,
  ""PFI Charges"": 0.0,
  ""In Year Balance"": -529000.0,
  ""Grant Funding"": 11506000.0,
  ""Direct Grant"": 10862000.0,
  ""Community Grants"": 30000.0,
  ""Targeted Grants"": 614000.0,
  ""Self Generated Funding"": 198000.0,
  ""Total Income"": 11540000.0,
  ""Supply Staff"": 170000.0,
  ""Other Staff Costs"": 556000.0,
  ""Staff Total"": 9653000.0,
  ""Maintenance & Improvement"": 253000.0,
  ""Premises"": 607000.0,
  ""Catering Exp"": 321000.0,
  ""Occupation"": 627000.0,
  ""Supplies and Services"": 1156000.0,
  ""Educational Supplies"": 501000.0,
  ""Brought in Professional Sevices"": 96000.0,
  ""Cost of Finance"": null,
  ""Community Exp"": null,
  ""Total Expenditure"": 12069000.0,
  ""TrustDidNotSubmit"": false,
  ""IsPlaceholder"": false,
  ""DNS"": false,
  ""WorkforcePresent"": true,
  ""SpecialNeedsPresent"": true,
  ""KS2Present"": true,
  ""KS4Present"": false,
  ""OfstedPresent"": true,
  ""CompanyNumberD8"": ""08179242"",
  ""TrustOrCompanyName"": ""Stour Academy Trust"",
  ""MATNumber"": null,
  ""CompanyNumber"": 8179242,
  ""Pre-16 Funding"": 10195000.0,
  ""RevenueReserveAsSubmitted"": 1518000.0,
  ""PartialYearsPresent"": false,
  ""LAEstab"": null,
  ""% of teachers with QTS"": null,
  ""FTE of Teaching Assistants"": null,
  ""FTE of Support Staff"": null,
  ""FTE of Admin Staff"": null,
  ""Average Key Stage 2 Point score"": null,
  ""% achieving Level 4 including English and Maths at KS2"": null,
  ""Average Attainment 8 score per pupil"": null,
  ""% with 5 A*-C grade GCSEs (or equiv) inc English and Maths"": null,
  ""Pupil Premium"": null,
  ""ESG"": null,
  ""Other Income"": null,
  ""Other"": null,
  ""Post-16 Funding"": null,
  ""ValidFrom"": null,
  ""ValidTo"": null,
  ""MemberCount"": 8.0,
  ""No Pupils"": 2015.0,
  ""No Teachers"": 114.5,
  ""Members"": [
    138579,
    141308,
    141881,
    140393,
    141548,
    145115,
    145013,
    138738
  ],
  ""Overall Phase"": ""Primary"",
  ""Revenue Reserve"": 1518000.0,
  ""last-modified-date-time"": ""05/03/2022 23:34:26"",
  ""id"": ""a1548264-1445-4045-ab5c-80e00adbcd69"",
  ""_rid"": ""qgt3AIbKQg9GAAAAAAAAAA=="",
  ""_self"": ""dbs/qgt3AA==/colls/qgt3AIbKQg8=/docs/qgt3AIbKQg9GAAAAAAAAAA==/"",
  ""_etag"": ""\""48025bde-0000-0d00-0000-63f4abe40000\"""",
  ""_attachments"": ""attachments/"",
  ""_ts"": 1676979172
}
";

        // act
        var parsed = JsonConvert.DeserializeObject<SchoolTrustFinancialDataObject>(document);

        // assert
        Assert.AreEqual(8179242, parsed.CompanyNumber);
        Assert.AreEqual(8, parsed.SchoolCount);
    }
}